/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesar;

import javax.swing.JOptionPane;

/**
 *
 * @author ardie
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbtnevents = new javax.swing.JLabel();
        txtbtnStatistika = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnDataMhs = new javax.swing.JButton();
        btnPaymentMhs = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtbtnevents.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        txtbtnevents.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtnevents.setText("Payment");
        txtbtnevents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtnevents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtneventsMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtnevents, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 150, 50));

        txtbtntmbhAnggota.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        txtbtntmbhAnggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtntmbhAnggota.setText("Kelola Mahasiswa");
        txtbtntmbhAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtntmbhAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtntmbhAnggotaMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtntmbhAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 210, 50));

        txtbtnStatistika.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        txtbtnStatistika.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtnStatistika.setText("Data Mahasiswa");
        txtbtnStatistika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtnStatistika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtnStatistikaMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtnStatistika, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 190, 50));

        jLabel1.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOGOUT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 80, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\IconLogout.png")); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 40, 40));

        tmbMhs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tmbMhs.setText("Management Mahasiswa");
        tmbMhs.setBorderPainted(false);
        tmbMhs.setContentAreaFilled(false);
        tmbMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tmbMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tmbMhsMouseClicked(evt);
            }
        });
        tmbMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmbMhsActionPerformed(evt);
            }
        });
        getContentPane().add(tmbMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 337, 220, 40));

        btnDataMhs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnDataMhs.setText("Data Mahasiswa");
        btnDataMhs.setBorderPainted(false);
        btnDataMhs.setContentAreaFilled(false);
        btnDataMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDataMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDataMhsMouseClicked(evt);
            }
        });
        btnDataMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDataMhsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDataMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 190, 40));

        btnPaymentMhs.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        btnPaymentMhs.setText("Payment");
        btnPaymentMhs.setBorderPainted(false);
        btnPaymentMhs.setContentAreaFilled(false);
        btnPaymentMhs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaymentMhs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPaymentMhsMouseClicked(evt);
            }
        });
        getContentPane().add(btnPaymentMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 190, 40));

        tampilNama.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        getContentPane().add(tampilNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 220, 40));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\System Management Anggota UKM.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDataMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDataMhsMouseClicked
        // TODO add your handling code here:
        new dataMHS().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnDataMhsMouseClicked

    private void btnPaymentMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPaymentMhsMouseClicked
        // TODO add your handling code here:
        new PaymentMhs().setVisible(true);
        JOptionPane.showMessageDialog(null, "Menu Payment hanya tersedia untuk Mahasiswa");
    }//GEN-LAST:event_btnPaymentMhsMouseClicked

    private void txtbtneventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtneventsMouseClicked
        // TODO add your handling code here:
        new PaymentMhs().setVisible(true);
        JOptionPane.showMessageDialog(null, "Menu Payment hanya tersedia untuk Mahasiswa");
    }//GEN-LAST:event_txtbtneventsMouseClicked

    private void txtbtntmbhAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtntmbhAnggotaMouseClicked
        // TODO add your handling code here:
        new TmbMahasiswa().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_txtbtntmbhAnggotaMouseClicked

    private void txtbtnStatistikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtnStatistikaMouseClicked
        // TODO add your handling code here:
        new dataMHS().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_txtbtnStatistikaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        new LoginPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tmbMhsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tmbMhsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tmbMhsMouseClicked

    private void tmbMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmbMhsActionPerformed
        // TODO add your handling code here:
        new TmbMahasiswa().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_tmbMhsActionPerformed

    private void btnDataMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDataMhsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDataMhsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnDataMhs;
    private javax.swing.JButton btnPaymentMhs;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static final javax.swing.JLabel tampilNama = new javax.swing.JLabel();
    public static final javax.swing.JButton tmbMhs = new javax.swing.JButton();
    private javax.swing.JLabel txtbtnStatistika;
    private javax.swing.JLabel txtbtnevents;
    public static final javax.swing.JLabel txtbtntmbhAnggota = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
