/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugasbesar;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author ardie
 */
public class dataMHS extends javax.swing.JFrame {

    /**
     * Creates new form dataMHS
     */
    public dataMHS() {
        initComponents();
        tampilkanData();
    }
    
    private void tampilkanData(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Nama");
        model.addColumn("NIM");
        model.addColumn("Email");
        model.addColumn("Gender");
        model.addColumn("Angkatan");
        model.addColumn("Semester");
        model.addColumn("Jurusan");
        model.addColumn("Fakultas");
        model.addColumn("Semester");
        model.addColumn("Infak");
        model.addColumn("Beasiswa");
        model.addColumn("Status Pembayaran");
        String cari = txtName.getText();
        try{
            java.sql.Connection conew =(Connection)dataConnection.configDB();
            String sql = "Select * from datamahasiswa where nama LIKE '"+cari+"%'";
            PreparedStatement pstn = conew.prepareStatement(sql);
            ResultSet rste = pstn.executeQuery();
            int no=1;
            while(rste.next()){
                model.addRow(new Object[]{no++, rste.getString(1), 
                    rste.getString(2), rste.getString(3), rste.getString(4), 
                    rste.getString(5), rste.getString(6), rste.getString(7), rste.getString(8), 
                    rste.getString(11), rste.getString(12), rste.getString(13), rste.getString(15)});
            }
            tableData.setModel(model);
            
        }catch(SQLException e){
            System.out.println("Error : " + e.getMessage());
        }
    }
    
    public void cari(){
        dataConnection dt = new dataConnection();
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtbtnStatistika = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        txtbtnevents = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(null);

        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableDataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(370, 250, 610, 290);

        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });
        getContentPane().add(txtName);
        txtName.setBounds(370, 190, 290, 30);

        jLabel2.setText("Search By Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(370, 220, 150, 14);

        txtbtnStatistika.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        txtbtnStatistika.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtnStatistika.setText("Data Mahasiswa");
        txtbtnStatistika.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtnStatistika.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtnStatistikaMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtnStatistika);
        txtbtnStatistika.setBounds(120, 190, 184, 27);

        txtbtntmbhAnggota.setFont(new java.awt.Font("Bookman Old Style", 1, 20)); // NOI18N
        txtbtntmbhAnggota.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtntmbhAnggota.setText("Kelola Mahasiswa");
        txtbtntmbhAnggota.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtntmbhAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtntmbhAnggotaMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtntmbhAnggota);
        txtbtntmbhAnggota.setBounds(120, 300, 183, 24);

        btnExit.setText("Keluar");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit);
        btnExit.setBounds(930, 100, 73, 23);

        txtbtnevents.setFont(new java.awt.Font("Bookman Old Style", 1, 22)); // NOI18N
        txtbtnevents.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txtbtnevents.setText("Payment");
        txtbtnevents.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtbtnevents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtbtneventsMouseClicked(evt);
            }
        });
        getContentPane().add(txtbtnevents);
        txtbtnevents.setBounds(120, 400, 102, 27);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\bgCari.png")); // NOI18N
        getContentPane().add(Background);
        Background.setBounds(0, 0, 1024, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableDataKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tableDataKeyPressed

    private void txtNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameKeyPressed

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        tampilkanData();
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtbtnStatistikaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtnStatistikaMouseClicked
        // TODO add your handling code here:
        new dataMHS().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_txtbtnStatistikaMouseClicked

    private void txtbtntmbhAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtntmbhAnggotaMouseClicked
        // TODO add your handling code here:
        new TmbMahasiswa().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_txtbtntmbhAnggotaMouseClicked

    private void txtbtneventsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtbtneventsMouseClicked
        // TODO add your handling code here:
        new PaymentMhs().setVisible(true);
        JOptionPane.showMessageDialog(null, "Menu Payment hanya tersedia untuk Mahasiswa");
    }//GEN-LAST:event_txtbtneventsMouseClicked

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataMHS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataMHS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableData;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtbtnStatistika;
    private javax.swing.JLabel txtbtnevents;
    public static final javax.swing.JLabel txtbtntmbhAnggota = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
