/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesar;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

import java.sql.*;
import static tugasbesar.Dashboard.tmbMhs;
import static tugasbesar.Dashboard.tampilNama;
import static tugasbesar.Profile.prfEmail;
import static tugasbesar.Profile.prfFakultas;
import static tugasbesar.Profile.prfGender;
import static tugasbesar.Profile.prfNama;
import static tugasbesar.Profile.prfNamaLabel;
import static tugasbesar.Profile.prfNim;
import static tugasbesar.Profile.prfPass;
import static tugasbesar.Profile.prfProdi;
import static tugasbesar.Profile.prfUser;


/**
 *
 * @author ardie
 */
public class LoginPage extends javax.swing.JFrame  {

    /**
     * Creates new form LoginPage
     */
    int countLog = 1;
    public LoginPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogin = new javax.swing.JButton();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Halaman Login");
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));

        btnLogin.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\Login.png")); // NOI18N
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        user.setBorder(null);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });

        pass.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pass.setBorder(null);

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\BGLogin.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(750, 750, 750)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(690, 690, 690)
                .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(Background)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Background)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(530, 530, 530)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection con =(Connection)dataConnection.configDB();
            String sql = "Select * from login where user=? and pass=?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, user.getText());
            pst.setString(2, pass.getText());
            ResultSet rs = pst.executeQuery();
            
            //mahasiswa 
            String sql1 = "SELECT * FROM datamahasiswa where usersmhs=? and passmhs=?";
            java.sql.Connection conn =(Connection)dataConnection.configDB();
            PreparedStatement pstm = conn.prepareStatement(sql1);
            pstm.setString(1, user.getText());
            pstm.setString(2, pass.getText());
            ResultSet res = pstm.executeQuery();
            if(countLog != 3){
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Username And Password Matched\nLogin Succesfull");
                    new Dashboard().setVisible(true);
                    setVisible(false);
                }
                else if(res.next()){
                    JOptionPane.showMessageDialog(null, "Username And Password Mahasiswa Matched");
                    new Profile().setVisible(true);
                    tampilNama.setText("Hello "+res.getString(1));
                    prfNamaLabel.setText("Hello "+res.getString(1));
                    tmbMhs.setEnabled(false);
                    prfNama.setText(res.getString(1));
                    prfNim.setText(res.getString(2));
                    prfEmail.setText(res.getString(3));
                    prfGender.setText(res.getString(4));
                    prfProdi.setText(res.getString(7));
                    prfFakultas.setText(res.getString(8));
                    prfUser.setText(res.getString(9));
                    prfPass.setText(res.getString(10));
                    setVisible(false);
                    
                }
                else{
                    JOptionPane.showMessageDialog(null,"Username Or Passwords Not Matched\nLogin Failed " + countLog + "/3" );
                    user.setText(null);
                    pass.setText(null);
                    countLog++;
                }
            }else{
                JOptionPane.showMessageDialog(null, "You Have Been Terminated :) ");
                System.exit(0); 
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        // TODO add your handling code here:
        

    }//GEN-LAST:event_btnLoginMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnLogin;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
