/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package tugasbesar;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ardie
 */
public class Profile extends javax.swing.JFrame {

    /** Creates new form Profile */
    public Profile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard Mahasiswa");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profile Mahasiswa");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Payment");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kelola Mahasiswa");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 305, -1, -1));

        prfUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfUserActionPerformed(evt);
            }
        });
        getContentPane().add(prfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 178, 30));

        prfNamaLabel.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        getContentPane().add(prfNamaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 200, 30));

        prfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfPassActionPerformed(evt);
            }
        });
        getContentPane().add(prfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 516, 178, 30));

        prfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(prfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 198, 178, 30));

        prfNim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfNimActionPerformed(evt);
            }
        });
        getContentPane().add(prfNim, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 243, 178, 30));

        prfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(prfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 288, 178, 30));

        prfGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfGenderActionPerformed(evt);
            }
        });
        getContentPane().add(prfGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 333, 178, 30));

        prfProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfProdiActionPerformed(evt);
            }
        });
        getContentPane().add(prfProdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 178, 30));

        prfFakultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfFakultasActionPerformed(evt);
            }
        });
        getContentPane().add(prfFakultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 423, 178, 30));

        prfUpdate.setText("Update");
        prfUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(prfUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 580, 120, 30));

        prfExit.setText("Keluar");
        prfExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prfExitActionPerformed(evt);
            }
        });
        getContentPane().add(prfExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 100, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ardie\\OneDrive\\Dokumen\\NetBeansProjects\\TugasBesar\\src\\tugasbesar\\icon\\bgProfill.png")); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prfUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfUserActionPerformed

    private void prfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfPassActionPerformed

    private void prfUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfUpdateActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please Contact Administrator!!\nCurrenty Under Development");
    }//GEN-LAST:event_prfUpdateActionPerformed

    private void prfExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfExitActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_prfExitActionPerformed

    private void prfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfNamaActionPerformed

    private void prfNimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfNimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfNimActionPerformed

    private void prfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfEmailActionPerformed

    private void prfGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfGenderActionPerformed

    private void prfProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfProdiActionPerformed

    private void prfFakultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prfFakultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prfFakultasActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new PaymentMhs().setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
        new Dashboard().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnKeluarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static final javax.swing.JTextField prfEmail = new javax.swing.JTextField();
    public static final javax.swing.JButton prfExit = new javax.swing.JButton();
    public static final javax.swing.JTextField prfFakultas = new javax.swing.JTextField();
    public static final javax.swing.JTextField prfGender = new javax.swing.JTextField();
    public static final javax.swing.JTextField prfNama = new javax.swing.JTextField();
    public static final javax.swing.JLabel prfNamaLabel = new javax.swing.JLabel();
    public static final javax.swing.JTextField prfNim = new javax.swing.JTextField();
    public static final javax.swing.JTextField prfPass = new javax.swing.JTextField();
    public static final javax.swing.JTextField prfProdi = new javax.swing.JTextField();
    public static final javax.swing.JButton prfUpdate = new javax.swing.JButton();
    public static final javax.swing.JTextField prfUser = new javax.swing.JTextField();
    // End of variables declaration//GEN-END:variables

}
